# Site settings
title: "FABERNOVEL, Inc. - Innovation Agency in San Francisco"
email: it@parisoma.com
description: "The innovation agency FABERNOVEL combines technology, design and emerging trends to invent new products, services and experiences. We help world leading companies to build growth at startup speed. Every day we bring entrepreneurs and large company experts together every day to launch breakthrough customer experiences."
baseurl: ""
url: "http://www.fabernovel.us"
twitter_username: fabernovel_us
github_username:  fabernovel





# Build settings
markdown: kramdown
permalink: pretty
